### ISSUE TITLE
@commercetools/ts-client is raising a DeprecationWarning for .data attribute

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-sdk-typescript#523]
It seems the @commercetools/ts-client is using `data` as input arg instead of `body`. This results in the following deprecation warning

```
[https://github.com/node-fetch/node-fetch/issues/1000 (request)] DeprecationWarning: .data is not a valid RequestInit property, use .body instead
    at new Request (file:///my-project/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:69:4)
    at file:///my-project/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///my-project/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:49:9)
    at execute (/my-project/node_modules/.pnpm/@commercetools+ts-client@1.1.0/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:172:14)
    at executeWithRetry (/my-project/node_modules/.pnpm/@commercetools+ts-client@1.1.0/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:190:29)
    at /my-project/node_modules/.pnpm/@commercetools+ts-client@1.1.0/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:211:28
    at sendRequest (/my-project/node_modules/.pnpm/@commercetools+ts-client@1.1.0/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:133:28)
    at executeHttpClientRequest (/my-project/node_modules/.pnpm/@commercetools+ts-client@1.1.0/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:145:10)
    at executor (/my-project/node_modules/.pnpm/@commercetools+ts-client@1.1.0/node_modules/@commercetools/ts-client/dist/commercetools-ts-client.cjs.dev.js:153:22)
```

The stacktrace is added via the node option `--trace-deprecation`

Might be due to https://github.com/commercetools/commercetools-sdk-typescript/blob/1bb77fcea8e5601dffd16438193de17d38cbfbef/packages/sdk-client-v3/src/utils/executor.ts#L113

**Comment by ajimae** [comment]
This has been fixed here. you can look [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/af2a168b58788513b2b228143172c7daa0d0c0ef/packages/sdk-client-v3/src/utils/executor.ts#L135)

**Comment by mvantellingen** [comment]
I don't believe this is currently fixed, I still see the same warning. It sets the `data` property if `res.body` is available, while it should not do that, because that triggers the deprecationwarning
